packages:
  - "apps/*"
  - "packages/**/*"
  - 'config/*'
  - 'docs'
  - 'mini-program/*'
catalog:
  "tailwindcss": "^3.4.10"
  "tailwindcss-animate": "^1.0.7"
  "@tailwindcss/typography": "^0.5.13"
  "postcss-preset-env": "^7.0.1"
  '@iconify/json': ^2.2.276
  '@iconify/tailwind': ^1.1.3
  '@manypkg/get-packages': ^2.2.2
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  postcss: ^8.4.49
  postcss-antd-fixes: ^0.2.0
  '@types/postcss-import': ^14.0.3
  postcss-import: ^16.1.0
  vite: ^5.4.10
  postcss-html: ^1.7.0
  postcss-scss: ^4.0.9
  prettier: ^3.4.1
  stylelint: ^16.10.0
  stylelint-config-recess-order: ^5.1.1
  stylelint-config-recommended: ^14.0.1
  stylelint-config-recommended-scss: ^14.1.0
  stylelint-config-recommended-vue: ^1.5.0
  stylelint-config-standard: ^36.0.1
  stylelint-order: ^6.0.4
  stylelint-prettier: ^5.0.2
  stylelint-scss: ^6.10.0
  '@stylistic/stylelint-plugin': ^3.1.1
  prettier-plugin-tailwindcss: ^0.6.9
  axios: ^1.7.8
  defu: ^6.1.4
  axios-mock-adapter: ^2.1.0
