packages:
  - "apps/*"
  - "packages/*"
  - 'config/*'
  - 'docs'
  - 'mini-program/*'
catalog:
  "tailwindcss": "^3.4.10"
  "tailwindcss-animate": "^1.0.7"
  "@tailwindcss/typography": "^0.5.13"
  "postcss-preset-env": "^7.0.1"