packages:
  - "apps/*"
  - "packages/*"
  - 'config/*'
  - 'docs'
  - 'mini-program/*'
catalog:
  "tailwindcss": "^3.4.10"
  "tailwindcss-animate": "^1.0.7"
  "@tailwindcss/typography": "^0.5.13"
  "postcss-preset-env": "^7.0.1"
  '@iconify/json': ^2.2.276
  '@iconify/tailwind': ^1.1.3
  '@manypkg/get-packages': ^2.2.2
  '@tailwindcss/nesting': 0.0.0-insiders.565cd3e
  autoprefixer: ^10.4.20
  cssnano: ^7.0.6
  postcss: ^8.4.49
  postcss-antd-fixes: ^0.2.0
  '@types/postcss-import': ^14.0.3
  postcss-import: ^16.1.0
  vite: ^6.0.1



